---
# Test values for chart-testing (ct install)
# Skips IMDS check since kind clusters don't have Azure IMDS

image:
  tag: "v2.2.0-3-g95187c2"

args:
  - "-skipIMDSCheck"

env:
  - name: ANTH_DEPLOYMENT_TEST
    value: "true"
